<?php
/**
 * @package   JEDSample
 * @copyright Copyright (c)2022 Nicholas K. Dionysopoulos
 * @license   GNU General Public License version 2, or later
 */

namespace Joomla\Plugin\Console\JEDSample\Util;

abstract class Constants
{
	/**
	 * All Faker locales (and language code) by country.
	 *
	 * @var   array
	 * @since 1.0.0
	 */
	public const LOCALES_PER_COUNTRY = [
		'CH' => ['it_CH', 'fr_CH', 'de_CH'],
		'CA' => ['en_CA', 'fr_CA'],
		'AT' => ['de_AT', 'at_AT'],
		'AR' => 'es_AR',
		'AU' => 'en_AU',
		'BE' => ['fr_BE', 'nl_BE'],
		'PH' => 'en_PH',
		'FR' => 'fr_FR',
		'GB' => 'en_GB',
		'NZ' => 'en_NZ',
		'DE' => 'de_DE',
		'US' => 'en_US',
		'SG' => 'en_SG',
		'ZA' => 'en_ZA',
		'CY' => 'el_CY',
		'NG' => 'en_NG',
		'NL' => 'nl_NL',
		'HK' => 'en_HK',
		'ES' => 'es_ES',
		'IT' => 'it_IT',
		'UG' => 'en_UG',
		'GR' => 'el_GR',
		'IN' => 'en_IN',
		'FI' => 'fi_FI',
		'VE' => 'es_VE',
		'LT' => 'lt_LT',
		'PT' => 'pt_PT',
		'SK' => 'sk_SK',
		'RO' => 'ro_RO',
		'BR' => 'pt_BR',
		'PL' => 'pl_PL',
		'HU' => 'hu_HU',
		'TR' => 'tr_TR',
		'DK' => 'da_DK',
		'CZ' => 'cs_CZ',
		'LV' => 'lv_LV',
		'NO' => 'nb_NO',
		'SE' => 'sv_SE',
		'PE' => 'es_PE',
		'RS' => ['sr_Cyrl_RS', 'sr_Latn_RS', 'sr_RS'],
		'HR' => 'hr_HR',
		'SI' => 'sl_SI',
		'BD' => 'bn_BD',
		'ME' => 'me_ME',
		'SA' => 'ar_SA',
		'UA' => 'uk_UA',
		'TW' => 'zh_TW',
		'AM' => 'hy_AM',
		'IR' => 'fa_IR',
		'BG' => 'bg_BG',
		'IS' => 'is_IS',
		'JO' => 'ar_JO',
		'TH' => 'th_TH',
		'NP' => 'ne_NP',
		'GE' => 'ka_GE',
		'MY' => 'ms_MY',
		'MN' => 'mn_MN',
		'MD' => 'ro_MD',
		'KR' => 'ko_KR',
		'ID' => 'id_ID',
		'CN' => 'zh_CN',
		'RU' => 'ru_RU',
		'JP' => 'ja_JP',
		'KZ' => 'kk_KZ',
		'VN' => 'vi_VN',
		'IL' => 'he_IL',
	];

	/**
	 * All locales, unsorted list
	 *
	 * @since 1.0.0
	 */
	public const LOCALES = [
		'it_CH',
		'fr_CH',
		'de_CH',
		'en_CA',
		'fr_CA',
		'de_AT',
		'at_AT',
		'es_AR',
		'en_AU',
		'fr_BE',
		'nl_BE',
		'en_PH',
		'fr_FR',
		'en_GB',
		'en_NZ',
		'de_DE',
		'en_US',
		'en_SG',
		'en_ZA',
		'el_CY',
		'en_NG',
		'nl_NL',
		'en_HK',
		'es_ES',
		'it_IT',
		'en_UG',
		'el_GR',
		'en_IN',
		'fi_FI',
		'es_VE',
		'lt_LT',
		'pt_PT',
		'sk_SK',
		'ro_RO',
		'pt_BR',
		'pl_PL',
		'hu_HU',
		'tr_TR',
		'da_DK',
		'cs_CZ',
		'lv_LV',
		'nb_NO',
		'sv_SE',
		'es_PE',
		'sr_Cyrl_RS',
		'sr_Latn_RS',
		'sr_RS',
		'hr_HR',
		'sl_SI',
		'bn_BD',
		'me_ME',
		'ar_SA',
		'uk_UA',
		'zh_TW',
		'hy_AM',
		'fa_IR',
		'bg_BG',
		'is_IS',
		'ar_JO',
		'th_TH',
		'ne_NP',
		'ka_GE',
		'ms_MY',
		'mn_MN',
		'ro_MD',
		'ko_KR',
		'id_ID',
		'zh_CN',
		'ru_RU',
		'ja_JP',
		'kk_KZ',
		'vi_VN',
		'he_IL',
	];

	/**
	 * All timezones per country code
	 *
	 * @var   array
	 * @since 1.0.0
	 *
	 * @see http://www.timezoneconverter.com/cgi-bin/zonehelp
	 */
	public const TIMEZONES_PER_COUNTRY = [
		'CH' => ['Europe/Zurich'],
		'CA' => [
			'America/St_Johns ', 'America/Halifax ', 'America/Glace_Bay ', 'America/Moncton ', 'America/Goose_Bay ',
			'America/Blanc-Sablon ', 'America/Toronto ', 'America/Nipigon ', 'America/Thunder_Bay ', 'America/Iqaluit ',
			'America/Pangnirtung ', 'America/Resolute ', 'America/Atikokan ', 'America/Rankin_Inlet ',
			'America/Winnipeg ', 'America/Rainy_River ', 'America/Regina ', 'America/Swift_Current ',
			'America/Edmonton ', 'America/Cambridge_Bay ', 'America/Yellowknife ', 'America/Inuvik ',
			'America/Creston ', 'America/Dawson_Creek ', 'America/Vancouver ', 'America/Whitehorse ', 'America/Dawson ',
		],
		'AT' => ['Europe/Vienna'],
		'AR' => [
			'America/Argentina/Buenos_Aires ', 'America/Argentina/Cordoba ', 'America/Argentina/Salta ',
			'America/Argentina/Jujuy ', 'America/Argentina/Tucuman ', 'America/Argentina/Catamarca ',
			'America/Argentina/La_Rioja ', 'America/Argentina/San_Juan ', 'America/Argentina/Mendoza ',
			'America/Argentina/San_Luis ', 'America/Argentina/Rio_Gallegos ', 'America/Argentina/Ushuaia ',
		],
		'AU' => [
			'Australia/Lord_Howe ', 'Antarctica/Macquarie ', 'Australia/Hobart ', 'Australia/Currie ',
			'Australia/Melbourne ', 'Australia/Sydney ', 'Australia/Broken_Hill ', 'Australia/Brisbane ',
			'Australia/Lindeman ', 'Australia/Adelaide ', 'Australia/Darwin ', 'Australia/Perth ', 'Australia/Eucla ',
		],
		'BE' => ['Europe/Brussels'],
		'PH' => ['Asia/Manila'],
		'FR' => ['Europe/Paris'],
		'GB' => ['Europe/London'],
		'NZ' => ['Pacific/Auckland', 'Pacific/Chatham'],
		'DE' => ['Europe/Berlin', 'Europe/Busingen'],
		'US' => [
			'America/New_York ', 'America/Detroit ', 'America/Kentucky/Louisville ', 'America/Kentucky/Monticello ',
			'America/Indiana/Indianapolis ', 'America/Indiana/Vincennes ', 'America/Indiana/Winamac ',
			'America/Indiana/Marengo ', 'America/Indiana/Petersburg ', 'America/Indiana/Vevay ', 'America/Chicago ',
			'America/Indiana/Tell_City ', 'America/Indiana/Knox ', 'America/Menominee ', 'America/North_Dakota/Center ',
			'America/North_Dakota/New_Salem ', 'America/North_Dakota/Beulah ', 'America/Denver ', 'America/Boise ',
			'America/Phoenix ', 'America/Los_Angeles ', 'America/Anchorage ', 'America/Juneau ', 'America/Sitka ',
			'America/Yakutat ', 'America/Nome ', 'America/Adak ', 'America/Metlakatla ', 'Pacific/Honolulu ',
		],
		'SG' => ['Asia/Singapore'],
		'ZA' => ['Africa/Johannesburg'],
		'CY' => ['Asia/Nicosia'],
		'NG' => ['Africa/Lagos'],
		'NL' => ['Europe/Amsterdam'],
		'HK' => ['Asia/Hong_Kong'],
		'ES' => ['Europe/Madrid', 'Africa/Ceuta', 'Atlantic/Canary'],
		'IT' => ['Europe/Rome'],
		'UG' => ['Africa/Kampala'],
		'GR' => ['Europe/Athens'],
		'IN' => ['Asia/Kolkata'],

		'FI' => ['Europe/Helsinki'],
		'VE' => ['America/Caracas'],
		'LT' => ['Europe/Vilnius'],
		'PT' => ['Europe/Lisbon', 'Atlantic/Madeira', 'Atlantic/Madeira'],
		'SK' => ['Europe/Bratislava'],
		'RO' => ['Europe/Bucharest'],
		'BR' => [
			'America/Noronha ', 'America/Belem ', 'America/Fortaleza ', 'America/Recife ', 'America/Araguaina ',
			'America/Maceio ', 'America/Bahia ', 'America/Sao_Paulo ', 'America/Campo_Grande ', 'America/Cuiaba ',
			'America/Santarem ', 'America/Porto_Velho ', 'America/Boa_Vista ', 'America/Manaus ', 'America/Eirunepe ',
			'America/Rio_Branco ',
		],
		'PL' => ['Europe/Warsaw'],
		'HU' => ['Europe/Budapest'],
		'TR' => ['Europe/Istanbul'],
		'DK' => ['Europe/Copenhagen'],
		'CZ' => ['Europe/Prague'],
		'LV' => ['Europe/Riga'],
		'NO' => ['Europe/Oslo'],
		'SE' => ['Europe/Stockholm'],
		'PE' => ['America/Lima'],

		'RS' => ['Europe/Belgrade'],
		'HR' => ['Europe/Zagreb'],
		'SI' => ['Europe/Ljubljana'],
		'BD' => ['Asia/Dhaka'],
		'ME' => ['Asia/Dhaka'],
		'SA' => ['Asia/Riyadh'],
		'UA' => ['Europe/Kiev', 'Europe/Uzhgorod', 'Europe/Zaporozhye'],
		'TW' => ['Asia/Taipei'],
		'AM' => ['Asia/Yerevan'],
		'IR' => ['Asia/Tehran'],
		'BG' => ['Europe/Sofia'],
		'IS' => ['Atlantic/Reykjavik'],
		'JO' => ['Asia/Amman'],
		'TH' => ['Asia/Bangkok'],
		'NP' => ['Asia/Kathmandu'],
		'GE' => ['Asia/Tbilisi'],
		'MY' => ['Asia/Kuala_Lumpur', 'Asia/Kuching'],
		'MN' => ['Asia/Ulaanbaatar', 'Asia/Hovd', 'Asia/Choibalsan'],
		'MD' => ['Europe/Chisinau'],
		'KR' => ['Asia/Seoul'],
		'ID' => ['Asia/Jakarta', 'Asia/Pontianak', 'Asia/Makassar', 'Asia/Jayapura'],
		'CN' => ['Asia/Shanghai ', 'Asia/Harbin ', 'Asia/Chongqing ', 'Asia/Urumqi ', 'Asia/Kashgar ',],
		'RU' => [
			'Europe/Kaliningrad ', 'Europe/Moscow ', 'Europe/Volgograd ', 'Europe/Samara ', 'Europe/Simferopol ',
			'Asia/Yekaterinburg ', 'Asia/Omsk ', 'Asia/Novosibirsk ', 'Asia/Novokuznetsk ', 'Asia/Krasnoyarsk ',
			'Asia/Irkutsk ', 'Asia/Yakutsk ', 'Asia/Khandyga ', 'Asia/Vladivostok ', 'Asia/Sakhalin ', 'Asia/Ust-Nera ',
			'Asia/Magadan ', 'Asia/Kamchatka ', 'Asia/Anadyr ',
		],
		'JP' => ['Asia/Tokyo'],
		'KZ' => ['Asia/Almaty ', 'Asia/Qyzylorda ', 'Asia/Aqtobe ', 'Asia/Aqtau ', 'Asia/Oral ',],
		'VN' => ['Asia/Ho_Chi_Minh'],
		'IL' => ['Asia/Jerusalem'],
	];

}